/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminThemeRouteImport } from './routes/_authenticated/admin.theme'
import { Route as AuthenticatedAdminRestaurantsRouteImport } from './routes/_authenticated/admin/restaurants'
import { Route as AuthenticatedAdminMenuViewRouteImport } from './routes/_authenticated/admin.menu-view'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin.menu'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminFlagsRouteImport } from './routes/_authenticated/admin.flags'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminRestaurantsNewRouteImport } from './routes/_authenticated/admin/restaurants/new'
import { Route as AuthenticatedAdminRestaurantsIdRouteImport } from './routes/_authenticated/admin/restaurants/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminThemeRoute = AuthenticatedAdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRestaurantsRoute =
  AuthenticatedAdminRestaurantsRouteImport.update({
    id: '/restaurants',
    path: '/restaurants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMenuViewRoute =
  AuthenticatedAdminMenuViewRouteImport.update({
    id: '/menu-view',
    path: '/menu-view',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFlagsRoute = AuthenticatedAdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRestaurantsNewRoute =
  AuthenticatedAdminRestaurantsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminRestaurantsRoute,
  } as any)
const AuthenticatedAdminRestaurantsIdRoute =
  AuthenticatedAdminRestaurantsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminRestaurantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/menu-view': typeof AuthenticatedAdminMenuViewRoute
  '/admin/restaurants': typeof AuthenticatedAdminRestaurantsRouteWithChildren
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
  '/admin/restaurants/new': typeof AuthenticatedAdminRestaurantsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/menu-view': typeof AuthenticatedAdminMenuViewRoute
  '/admin/restaurants': typeof AuthenticatedAdminRestaurantsRouteWithChildren
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
  '/admin/restaurants/new': typeof AuthenticatedAdminRestaurantsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/admin/menu-view': typeof AuthenticatedAdminMenuViewRoute
  '/_authenticated/admin/restaurants': typeof AuthenticatedAdminRestaurantsRouteWithChildren
  '/_authenticated/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
  '/_authenticated/admin/restaurants/new': typeof AuthenticatedAdminRestaurantsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/invite/$token'
    | '/admin/categories'
    | '/admin/flags'
    | '/admin/members'
    | '/admin/menu'
    | '/admin/menu-view'
    | '/admin/restaurants'
    | '/admin/theme'
    | '/admin/'
    | '/admin/restaurants/$id'
    | '/admin/restaurants/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invite/$token'
    | '/admin/categories'
    | '/admin/flags'
    | '/admin/members'
    | '/admin/menu'
    | '/admin/menu-view'
    | '/admin/restaurants'
    | '/admin/theme'
    | '/admin'
    | '/admin/restaurants/$id'
    | '/admin/restaurants/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/invite/$token'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/flags'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/menu'
    | '/_authenticated/admin/menu-view'
    | '/_authenticated/admin/restaurants'
    | '/_authenticated/admin/theme'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/restaurants/$id'
    | '/_authenticated/admin/restaurants/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/theme': {
      id: '/_authenticated/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AuthenticatedAdminThemeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/restaurants': {
      id: '/_authenticated/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/menu-view': {
      id: '/_authenticated/admin/menu-view'
      path: '/menu-view'
      fullPath: '/admin/menu-view'
      preLoaderRoute: typeof AuthenticatedAdminMenuViewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/flags': {
      id: '/_authenticated/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AuthenticatedAdminFlagsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/restaurants/new': {
      id: '/_authenticated/admin/restaurants/new'
      path: '/new'
      fullPath: '/admin/restaurants/new'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRestaurantsRoute
    }
    '/_authenticated/admin/restaurants/$id': {
      id: '/_authenticated/admin/restaurants/$id'
      path: '/$id'
      fullPath: '/admin/restaurants/$id'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRestaurantsRoute
    }
  }
}

interface AuthenticatedAdminRestaurantsRouteChildren {
  AuthenticatedAdminRestaurantsIdRoute: typeof AuthenticatedAdminRestaurantsIdRoute
  AuthenticatedAdminRestaurantsNewRoute: typeof AuthenticatedAdminRestaurantsNewRoute
}

const AuthenticatedAdminRestaurantsRouteChildren: AuthenticatedAdminRestaurantsRouteChildren =
  {
    AuthenticatedAdminRestaurantsIdRoute: AuthenticatedAdminRestaurantsIdRoute,
    AuthenticatedAdminRestaurantsNewRoute:
      AuthenticatedAdminRestaurantsNewRoute,
  }

const AuthenticatedAdminRestaurantsRouteWithChildren =
  AuthenticatedAdminRestaurantsRoute._addFileChildren(
    AuthenticatedAdminRestaurantsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminFlagsRoute: typeof AuthenticatedAdminFlagsRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedAdminMenuViewRoute: typeof AuthenticatedAdminMenuViewRoute
  AuthenticatedAdminRestaurantsRoute: typeof AuthenticatedAdminRestaurantsRouteWithChildren
  AuthenticatedAdminThemeRoute: typeof AuthenticatedAdminThemeRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminFlagsRoute: AuthenticatedAdminFlagsRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
  AuthenticatedAdminMenuViewRoute: AuthenticatedAdminMenuViewRoute,
  AuthenticatedAdminRestaurantsRoute:
    AuthenticatedAdminRestaurantsRouteWithChildren,
  AuthenticatedAdminThemeRoute: AuthenticatedAdminThemeRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
